In [70]:
from find_cluster_degs import *
adata = read('/home/zuolulu/spatialDEG/test/results.h5ad')
adata

AnnData object with n_obs × n_vars = 3639 × 19130
    obs: 'x1', 'x2', 'x3', 'x4', 'x5', 'n_counts', 'pred', 'refined_pred', 'x_array', 'y_array', 'x_pixel', 'y_pixel', 'group'
    var: 'gene_ids', 'feature_types', 'genome', 'genename'
    uns: 'pred_colors', 'refined_pred_colors'

In [71]:
cell_id = adata.obs.index.tolist()
x = adata.obs['x_array'].tolist()
y = adata.obs['y_array'].tolist()
group=adata.obs['group'].tolist()
test_group = 0

In [ ]:
adata.obs[adata.obs['x_array']==51]

In [73]:
X=np.array([x, y]).T.astype(np.float32)
adj = distance.cdist(X, X, 'euclidean')
adj

array([[ 0.        , 75.43208866, 83.48652586, ..., 75.16648189,
        65.19202405, 66.70832032],
       [75.43208866,  0.        , 60.92618485, ..., 44.94441011,
        70.0285656 ,  8.94427191],
       [83.48652586, 60.92618485,  0.        , ..., 16.1245155 ,
        26.07680962, 61.05735009],
       ...,
       [75.16648189, 44.94441011, 16.1245155 , ...,  0.        ,
        31.30495168, 44.94441011],
       [65.19202405, 70.0285656 , 26.07680962, ..., 31.30495168,
         0.        , 66.75327707],
       [66.70832032,  8.94427191, 61.05735009, ..., 44.94441011,
        66.75327707,  0.        ]])

In [74]:
df = {'cell_id': cell_id, 'x': x, "y":y, "group":group}
df = pd.DataFrame(data=df)
df.index=df['cell_id']
test_df=df[df["group"]==test_group]
row_index=0
num_nbr=[]

In [85]:
test_df.loc[:,['x','y']]
df

cell_id   x    y  group
cell_id                                               
AAACAAGTATCTCCCA-1  AAACAAGTATCTCCCA-1  50  102      3
AAACAATCTACTAGCA-1  AAACAATCTACTAGCA-1   3   43      2
AAACACCAATAACTGC-1  AAACACCAATAACTGC-1  59   19      5
AAACAGAGCGACTCCT-1  AAACAGAGCGACTCCT-1  14   94      0
AAACAGCTTTCAGAAG-1  AAACAGCTTTCAGAAG-1  43    9      6
...                                ...  ..  ...    ...
TTGTTTCACATCCAGG-1  TTGTTTCACATCCAGG-1  58   42      5
TTGTTTCATTAGTCTA-1  TTGTTTCATTAGTCTA-1  60   30      5
TTGTTTCCATACAACT-1  TTGTTTCCATACAACT-1  45   27      4
TTGTTTGTATTACACG-1  TTGTTTGTATTACACG-1  73   41      4
TTGTTTGTGTAAATTC-1  TTGTTTGTGTAAATTC-1   7   51      0

[3639 rows x 4 columns]

In [78]:
for index,row in test_df.iterrows():
    print(index,row)

AAACAGAGCGACTCCT-1 cell_id    AAACAGAGCGACTCCT-1
x                          14
y                          94
group                       0
Name: AAACAGAGCGACTCCT-1, dtype: object
AAACATTTCCCGGATT-1 cell_id    AAACATTTCCCGGATT-1
x                          61
y                          97
group                       0
Name: AAACATTTCCCGGATT-1, dtype: object
AAACCCGAACGAAATC-1 cell_id    AAACCCGAACGAAATC-1
x                          45
y                         115
group                       0
Name: AAACCCGAACGAAATC-1, dtype: object
AAACGAAGAACATACC-1 cell_id    AAACGAAGAACATACC-1
x                           6
y                          64
group                       0
Name: AAACGAAGAACATACC-1, dtype: object
AAACTCGTGATATAAG-1 cell_id    AAACTCGTGATATAAG-1
x                          23
y                         113
group                       0
Name: AAACTCGTGATATAAG-1, dtype: object
AAAGACCCAAGTCGCG-1 cell_id    AAAGACCCAAGTCGCG-1
x                          10
y                         

In [79]:
for index, row in test_df.iterrows():
    x=row["x"]
    y=row["y"]
    tmp_nbr=df[((df["x"]-x)**2+(df["y"]-y)**2)<=(5**2)]
    num_nbr.append(tmp_nbr.shape[0])
np.mean(num_nbr)

34.655313351498634

In [80]:
tmp_nbr

cell_id   x   y  group
cell_id                                              
AAAGACCCAAGTCGCG-1  AAAGACCCAAGTCGCG-1  10  48      0
AAAGTCACTGATGTAA-1  AAAGTCACTGATGTAA-1  10  52      0
AACTAGCGTATCGCAC-1  AACTAGCGTATCGCAC-1   4  48      2
AACTGGTGTGGGCCTT-1  AACTGGTGTGGGCCTT-1   7  49      0
AACTTTAGCTGCTGAG-1  AACTTTAGCTGCTGAG-1   5  49      2
ACCGAAAGGGCCCTGC-1  ACCGAAAGGGCCCTGC-1   9  53      0
ACGTTCCGCGCTCCGT-1  ACGTTCCGCGCTCCGT-1   8  54      0
AGACATAGATCCTTCC-1  AGACATAGATCCTTCC-1   7  47      0
AGAGGTATCTCGGTCC-1  AGAGGTATCTCGGTCC-1   3  51      2
AGCTTATAGAGACCTG-1  AGCTTATAGAGACCTG-1   5  47      2
ATACCAGGCTAATAGA-1  ATACCAGGCTAATAGA-1   9  55      0
ATGCATTCCGTGATGG-1  ATGCATTCCGTGATGG-1   4  52      1
ATTCTCGTCTCTTTAG-1  ATTCTCGTCTCTTTAG-1  11  51      0
CAAGTGAACTTTGGTT-1  CAAGTGAACTTTGGTT-1   6  54      0
CACGACTAAAGTTCTG-1  CACGACTAAAGTTCTG-1   3  49      2
CCCAAGACAGAGTATG-1  CCCAAGACAGAGTATG-1   4  50      2
CGTAGCGCCGACGTTG-1  CGTAGCGCCGACGTTG-1   7  53      0
CGTCAGTGCGCACAAG-1  CGTCAGTGCGCACAAG-1  11  49      0
GAACCATCTGGGAGAC-1  GAACCATCTGGGAGAC-1   4  54      0
GAGCCACGGTAGTAGG-1  GAGCCACGGTAGTAGG-1   9  47      0
GCCGGAAACACATCTT-1  GCCGGAAACACATCTT-1   3  53      2
GCCTATTTGCTACACA-1  GCCTATTTGCTACACA-1   8  50      0
GGATCAAAGGACGAGG-1  GGATCAAAGGACGAGG-1   6  52      2
GGCATCAACGAGCACG-1  GGCATCAACGAGCACG-1   5  51      0
GGTGAAACCGGGAATG-1  GGTGAAACCGGGAATG-1   6  48      2
GTAGACAACCGATGAA-1  GTAGACAACCGATGAA-1   7  55      0
GTAGCGCTGTTGTAGT-1  GTAGCGCTGTTGTAGT-1   6  50      0
TAACCGCCCGCAGTGC-1  TAACCGCCCGCAGTGC-1   9  49      0
TCGATAGGCTAGTCGC-1  TCGATAGGCTAGTCGC-1   8  48      0
TGCTATACAAACGGAC-1  TGCTATACAAACGGAC-1   5  55      0
TGTATCCTTATTCCAT-1  TGTATCCTTATTCCAT-1  10  50      0
TGTCTACAGTTTCTGT-1  TGTCTACAGTTTCTGT-1  11  53      3
TTAAACCGGTAGCGAC-1  TTAAACCGGTAGCGAC-1   8  52      0
TTAACGTCGCAAGACC-1  TTAACGTCGCAAGACC-1  10  54      0
TTATAGATGCACATTA-1  TTATAGATGCACATTA-1   5  53      0
TTGACGATTCAGCACG-1  TTGACGATTCAGCACG-1   9  51      0
TTGTTTGTGTAAATTC-1  TTGTTTGTGTAAATTC-1   7  51      0

In [82]:
adata.obs['group'==0]
x = adata.obs['x_array'].tolist()
y = adata.obs['y_array'].tolist()
XYmap = pd.DataFrame({'x': x, "y":y})
XYmap

x    y
0     50  102
1      3   43
2     59   19
3     14   94
4     43    9
...   ..  ...
3634  58   42
3635  60   30
3636  45   27
3637  73   41
3638   7   51

[3639 rows x 2 columns]

In [88]:
from sklearn.neighbors import NearestNeighbors
XYnbrs = NearestNeighbors(n_neighbors=20, algorithm='auto',metric = 'euclidean').fit(XYmap)
XYdistances, XYindices = XYnbrs.kneighbors(XYmap)
XYdistances

array([[0.        , 1.41421356, 1.41421356, ..., 3.16227766, 3.16227766,
        3.16227766],
       [0.        , 1.41421356, 1.41421356, ..., 4.        , 4.24264069,
        4.24264069],
       [0.        , 1.41421356, 1.41421356, ..., 3.16227766, 3.16227766,
        3.16227766],
       ...,
       [0.        , 1.41421356, 1.41421356, ..., 3.16227766, 3.16227766,
        3.16227766],
       [0.        , 1.41421356, 1.41421356, ..., 4.47213595, 5.09901951,
        5.09901951],
       [0.        , 1.41421356, 1.41421356, ..., 3.16227766, 3.16227766,
        3.16227766]])

In [112]:
XYindices

array([[   0, 3542, 2121, ..., 1211, 2953,   43],
       [   1, 1617, 2334, ..., 3329, 1097, 2619],
       [   2, 3311, 1714, ..., 3584, 2629,  255],
       ...,
       [3636, 1817, 3409, ..., 1774, 1761,    9],
       [3637, 2101, 1974, ..., 1788, 2646,  594],
       [3638, 2307, 2506, ...,  388, 1229, 2448]])

In [113]:
XYmap.loc[XYindices[2,:]]

x   y
2     59  19
3311  58  20
1714  60  18
3024  58  18
1849  60  20
2372  57  19
580   59  17
2280  59  21
765   61  19
2895  61  17
2747  61  21
2926  57  17
1723  57  21
505   56  20
2533  56  18
2523  58  22
993   60  22
3584  62  18
2629  58  16
255   60  16

In [117]:
x = adata.obs['x_array'].tolist()
y = adata.obs['y_array'].tolist()
group=adata.obs['group'].tolist()
df = pd.DataFrame({'x':x,'y':y,'group':group})
df
target_df=df[df["group"]==0]
target_df
group=[0,1,2,3,4,5,6]
group_num = dict()
for i in group:
    group_num[i] = df['group'].value_counts()[i]
group_num    

3 x        14
y        94
group     0
Name: 3, dtype: int64
7 x        61
y        97
group     0
Name: 7, dtype: int64
8 x         45
y        115
group      0
Name: 8, dtype: int64
13 x         6
y        64
group     0
Name: 13, dtype: int64
18 x         23
y        113
group      0
Name: 18, dtype: int64
23 x        10
y        48
group     0
Name: 23, dtype: int64
32 x        10
y        52
group     0
Name: 32, dtype: int64
37 x         31
y        115
group      0
Name: 37, dtype: int64
39 x         36
y        106
group      0
Name: 39, dtype: int64
43 x         53
y        101
group      0
Name: 43, dtype: int64
44 x         21
y        111
group      0
Name: 44, dtype: int64
45 x        16
y        24
group     0
Name: 45, dtype: int64
55 x         6
y        90
group     0
Name: 55, dtype: int64
67 x         49
y        113
group      0
Name: 67, dtype: int64
74 x         6
y        92
group     0
Name: 74, dtype: int64
76 x        14
y        30
group     0
Name: 76, dtype:

In [161]:
x = adata.obs['x_array'].tolist()
y = adata.obs['y_array'].tolist()
XYmap = pd.DataFrame({'x': x, "y":y})
XYnbrs = NearestNeighbors(n_neighbors=20, algorithm='auto',metric = 'euclidean').fit(XYmap)
XYdistances, XYindices = XYnbrs.kneighbors(XYmap)
XYdistances
nbr_0=XYindices[target_df.index]
nbr_0

array([[   3, 2241, 1064, ...,  231, 2615, 1276],
       [   7,  733, 1358, ..., 1842, 2814, 1480],
       [   8, 3570, 2624, ..., 1426, 1900, 2585],
       ...,
       [3614,  447, 1814, ..., 2994, 1252, 2191],
       [3628, 1480, 3452, ...,  746, 2521,  733],
       [3638, 2307, 2506, ...,  388, 1229, 2448]])

In [169]:
nbr_0[0][1]

2241

In [200]:
nbr_0_unique=np.unique(nbr_0)
nbr_0_unique

array([   0,    1,    3, ..., 3614, 3628, 3638])

In [207]:
nbr_0_unique=np.unique(nbr_0)
group_id=[]
for x in np.nditer(nbr_0_unique):
    group_id.append(df.loc[x,'group'])
from collections import Counter
nbr_0_group = Counter(group_id)
nbr_0_group


Counter({3: 285, 2: 207, 0: 734, 6: 30, 1: 21, 4: 7})

In [208]:
group_num

{0: 734, 1: 555, 2: 368, 3: 595, 4: 405, 5: 430, 6: 552}

In [211]:
207/368

0.5625

In [237]:
group=[0,1,2,3,4,5,6]
group_num = dict()
ratio=dict()
for i in group:
    group_num[i] = df['group'].value_counts()[i]
    ratio[i] = nbr_0_group[i]/group_num[i]
nbr_0_group
ratio

{0: 1.0,
 1: 0.03783783783783784,
 2: 0.5625,
 3: 0.4789915966386555,
 4: 0.01728395061728395,
 5: 0.0,
 6: 0.05434782608695652}

In [242]:
ratio.values()
result = [i for i, e in enumerate(ratio.values()) if e > 0.5]
result

[0, 2]

In [131]:
target_df

x    y  group
3     14   94      0
7     61   97      0
8     45  115      0
13     6   64      0
18    23  113      0
...   ..  ...    ...
3599   8   78      0
3602  51  105      0
3614  51  109      0
3628  63   95      0
3638   7   51      0

[734 rows x 3 columns]

In [249]:
from spatial_cluster_degs import *
x = adata.obs['x_array'].tolist()
y = adata.obs['y_array'].tolist()
calculate_adj_matrix(x, y, image=None,)

array([[ 0.        , 75.43208866, 83.48652586, ..., 75.16648189,
        65.19202405, 66.70832032],
       [75.43208866,  0.        , 60.92618485, ..., 44.94441011,
        70.0285656 ,  8.94427191],
       [83.48652586, 60.92618485,  0.        , ..., 16.1245155 ,
        26.07680962, 61.05735009],
       ...,
       [75.16648189, 44.94441011, 16.1245155 , ...,  0.        ,
        31.30495168, 44.94441011],
       [65.19202405, 70.0285656 , 26.07680962, ..., 31.30495168,
         0.        , 66.75327707],
       [66.70832032,  8.94427191, 61.05735009, ..., 44.94441011,
        66.75327707,  0.        ]])

In [ ]:
from find_cluster_degs import *
adata = read('/home/zuolulu/spatialDEG/test/results.h5ad')
genes = ['CAMK2N1','ENC1','HPCAL1','CCK','HOPX','MALAT1','SERPINE2','TESPA1','RASGRF2','FKBP1A']
#degs = find_cluster_degs(adata,group='group',test_group=5,control_groups=[1,2,3,4,5,6],genes=None)
#adata = find_all_cluster_degs(adata,group='group',genes=None)
degs


identifying top markers for each group: 19130it [04:28, 71.30it/s]
identifying top markers for each group: 19130it [04:39, 68.51it/s]
identifying top markers for each group: 19130it [04:32, 70.26it/s]
identifying top markers for each group: 19130it [04:21, 73.04it/s]
identifying top markers for each group: 19130it [04:38, 68.69it/s]
identifying top markers for each group: 19130it [04:31, 70.52it/s]
identifying top markers for each group: 19130it [04:32, 70.25it/s]
identifying top markers for each group: 19130it [04:32, 70.11it/s]


NameError: name 'NearestNeighbors' is not defined

In [1]:
from find_cluster_degs import *
adata = read('/home/zuolulu/spatialDEG/test/results.h5ad')
spa_degs = find_spatial_cluster_degs(test_group=5,adata=adata,x=None,y=None,group='group')

identifying top markers for each group: 9414it [02:07, 76.64it/s]

In [68]:
from spatial_cluster_degs import *
adata = read('/home/zuolulu/spatialDEG/test/results.h5ad')
# get x,y
group='group'
x = adata.obs['x_array'].tolist()
y = adata.obs['y_array'].tolist()
group = adata.obs[group].tolist()

df = pd.DataFrame({'x': x, 'y': y, 'group': group})
test_df = df[df["group"]==1]
#find_neighbor_groups(test_group=0,adata=adata,x=None,y=None,group='group')

In [69]:
XYmap = pd.DataFrame({'x': x, "y": y})
XYnbrs = NearestNeighbors(n_neighbors=20, algorithm='auto', metric='euclidean').fit(XYmap)
_, XYindices = XYnbrs.kneighbors(XYmap)
nbr_id = XYindices[test_df.index]
nbr_id

array([[  33, 2387, 3358, ..., 3383, 1158,  859],
       [  40,  169, 2686, ...,  999,  794,  961],
       [  57, 1380, 1955, ...,  395,  824, 3067],
       ...,
       [3625, 1965,  370, ..., 1450,  988, 2816],
       [3626,  530, 1696, ..., 3596,  724, 1897],
       [3633, 1308,  426, ..., 3437, 1058, 2446]])

In [70]:
## neighbor count
nbr_id_unique = np.unique(nbr_id)
group_id = []
for x in np.nditer(nbr_id_unique):
    group_id.append(df.loc[x, 'group'])
nbr_group = Counter(group_id)
nbr_group

Counter({3: 434, 0: 98, 6: 311, 1: 555, 2: 79, 4: 25})

In [71]:
## ratio
group=[0,1,2,3,4,5,6]
group_num = dict()
ratio = dict()
for i in group:
    group_num[i] = df['group'].value_counts()[i]
    ratio[i] = nbr_group[i]/group_num[i]
nbr_group
ratio

{0: 0.1335149863760218,
 1: 1.0,
 2: 0.21467391304347827,
 3: 0.7294117647058823,
 4: 0.06172839506172839,
 5: 0.0,
 6: 0.5634057971014492}

In [89]:
test_group=1
ratio.values()
result = [i for i, e in enumerate(ratio.values()) if e > 0.5]
result.remove(test_group)
result

[3, 6]